# Generated by Django 3.2.5 on 2021-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('about', models.TextField(verbose_name='Описание')),
                ('weekday', models.TextField(verbose_name='Будни')),
                ('weekend_friday', models.TextField(verbose_name='Пятница')),
                ('weekend_saturday', models.TextField(verbose_name='Суббота')),
                ('new_year', models.TextField(verbose_name='Новый год')),
                ('pre_new_year_weekday', models.TextField(verbose_name='Предновогодние будни')),
                ('pre_new_year_weekend', models.TextField(verbose_name='Предновогодние выходные')),
                ('postscript', models.CharField(max_length=100, verbose_name='Приписка')),
            ],
            options={
                'verbose_name': 'Коттедж',
                'verbose_name_plural': 'Коттеджи',
            },
        ),
    ]
