# Generated by Django 3.2.5 on 2021-08-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Коттедж', to='app.cottage')),
            ],
        ),
    ]
