# Generated by Django 3.2.5 on 2021-08-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210824_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photo_webm',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_webp',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография.webp'),
        ),
    ]
